version: '3.9'

services:
  esep-db:
    image: postgres:14
    container_name: esep-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: esep
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  esep-backend:
    build: .
    depends_on:
      - esep-db
    env_file:
      - docker.env
    network_mode: host
    container_name: esep-backend
    restart: always
    command: "--migrate --dev"
  
  esep-jeager:
    image: jaegertracing/all-in-one:latest
    network_mode: host
    container_name: esep-jeager
    restart: always
    ports:
      - 16686:16686
      - 14268:14268

  esep-grafana:
    image: grafana/grafana:latest
    container_name: esep-grafana
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: host
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel"
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
