---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounter-backend
  namespace: accounter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounter-backend
  template:
    metadata:
      labels:
        app: accounter-backend
    spec:
      containers:
      - name: accounter-backend
        image: accounter-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health/ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: accounter-backend
  namespace: accounter
spec:
  type: NodePort
  selector:
    app: accounter-backend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
